// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGx-R048_3d5i3A-AojqnV4UnZTRhHJxc',
    appId: '1:589651569431:web:54cc349058edf210042552',
    messagingSenderId: '589651569431',
    projectId: 'talkie-58bf9',
    authDomain: 'talkie-58bf9.firebaseapp.com',
    storageBucket: 'talkie-58bf9.appspot.com',
    measurementId: 'G-8JD23NRSPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAolesyVXaQj6GwXv6wSXIWLn8bU15q9So',
    appId: '1:589651569431:android:9d058b2b93be3e56042552',
    messagingSenderId: '589651569431',
    projectId: 'talkie-58bf9',
    storageBucket: 'talkie-58bf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSWhYrM_NxazPoIqGQc5BgCv_xJioFnDg',
    appId: '1:589651569431:ios:7f9c8967c0c1c163042552',
    messagingSenderId: '589651569431',
    projectId: 'talkie-58bf9',
    storageBucket: 'talkie-58bf9.appspot.com',
    iosClientId: '589651569431-tji6sevfe4ps23giqd9esrlcqfn70sup.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSWhYrM_NxazPoIqGQc5BgCv_xJioFnDg',
    appId: '1:589651569431:ios:8b04d8dcd61ff587042552',
    messagingSenderId: '589651569431',
    projectId: 'talkie-58bf9',
    storageBucket: 'talkie-58bf9.appspot.com',
    iosClientId: '589651569431-rmnds8c8cbgsd77ab7m8agjm0lqdnefm.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkie.RunnerTests',
  );
}
